### PR TITLE
Create Messages

### PR DESCRIPTION
**Pull request by rquesada**
# Summary
This PR create the object Message and MessageCreate
 
# Changes
 
- [x] Added Message schema
- [x] Added Message
- [x] Added MessageCreate

 
# Related Issues
N/A
 
# Type of Change
New feature (non-breaking change which adds functionality)
 
# Checklist 
- [x] I have read the [CONTRIBUTING](https://github.com/pAI-OS/paios/blob/main/CONTRIBUTING.md) documentation.
- [x]  I have performed a self-review of my own code.
- [x]  I have added tests that prove my fix is effective or that my feature works.
- [x]  I have updated the documentation (if applicable).
 
# Screenshots (if applicable)
Screenshot 2024-07-29 at 1 55 09 PM
Screenshot 2024-07-29 at 1 56 22 PM

 
# Additional Context
Tested locally using Swagger. Right now the chat response contained the message create response is hard coded.

### CODE REVIEW

**Review by quaid — COMMENTED** [review]
Dropping my notes in here for trying to figure out the GPG signing problem for #7 , #8 #9 & #10 

I'm looking at the half-broken GPG check step, it seems to be the same error in each of the four open PRs:
248  Error: Some commits have signature verification issues.
[249](https://github.com/pAI-OS/paios/actions/runs/10115868330/job/27978083840?pr=7#step:4:250)  GPG signature verification failed or encountered an error.
[250](https://github.com/pAI-OS/paios/actions/runs/10115868330/job/27978083840?pr=7#step:4:251)  Error: Process completed with exit code 1.
Looking back up in the output the only warning is one of these, and it's the same for both 
[@Ana Pacheco](https://kwaaiailab.slack.com/team/U068GCFJ4P7)
 and 
[@Roy Quesada](https://kwaaiailab.slack.com/team/U06CL0ZQVTK)
.
160  Warning: Commit 5395785445e7eeea15ed48cb52e2955f58ba59a4 by Ana Pacheco <[144283863+AnniePachecoJ@users.noreply.github.com](mailto:144283863+AnniePachecoJ@users.noreply.github.com)> is signed by GitHub (likely made through web interface or API) (ed

**Comment by samj** [comment]
“160 Warning: Commit 5395785 by Ana Pacheco ***@***.***> *is signed by GitHub (likely made through web interface or API)*”

Hard reset and resend with it signed by your own key.

Sent via Superhuman iOS ( ***@***.*** )

**Comment by samj** [comment]
Clobbers openai/openapi.yaml (hence the large red negative count top right).

**Comment by samj** [comment]
Very interesting idea to have the OS track message logs... wasn't something I'd considered but does make a lot of sense.

It does put us right into the data plane though with transactional data and potentially scaling headaches. Conversely, if we don't do it, everyone has to, and we don't want e.g. assistants spinning up their own SQL servers.

Need to think about/discuss this; shame we didn't have a chance to this week.

**Comment by samj** [comment]
You're targeting develop, not main (which is expected to be a working branch).

**Comment by samj** [comment]
As I study for my Azure AZ-104 exam tomorrow, I appreciate their separation of management and data plane. Management (which is what pAI-OS is concerned with) is things like **_creating_** a file share mountable on end-user devices. Data is the actual **_access_** to that share. One is a very small request that happens very infrequently (ie on CRUD activities relating to the share itself), while the other is ongoing, high bandwidth, low latency access, similar to what messages would be in a high-frequency deployment.

That's not to say we can't handle it e.g. by using a relational database, but that perhaps we shouldn't. I've created issue #27 on the topic so we don't forget to come back to it, but I don't want this to block progress on the assistant so I suggest we either solve it or find an alterantive.

**Comment by samj** [comment]
I'm leaning in the direction of accepting this PR on the basis that otherwise you have to install your own yourselves, which is arguably the worse of two evils. It does mean that we need to give more consideration to scalability issues in the OS for larger deployments (or give them a way to circumvent us), but for most deployments it shouldn't be a problem even with sqlite3.

We do need to give some more consideration to the data storage format, but it will likely want to be a hybrid of fixed fields for common items like timestamp, with the ability to extend with arbitrary attributes/objects (again likely using sqlite/mysql/postgres native support of JSON).

Thanks for taking us down this track — I would have excluded the idea to stay out of the data plane but it's growing on me.

**Comment by samj** [comment]
As an example of data format considerations, the conversation discussion @rquesada is going through on the weekly call right now is a good example. For example, we could save the conversation as a single row including all the interactions, or we could have a conversation with a one-to-many to individual messages, which starts to get into the performance issues again (there is still the question of bloat given conversations can include media).

**Comment by buzzaz** [comment]
Sam I'm wondering If the data connection can be changed later on, or if
that would mean technical debt. I am getting into databricks, which allows
data lake as well as data warehouse connectivity. Do you feel that we would
be able to modify the database connection later on should it be required?
If not, might the decision of which database we're using warrant some more
forethought?

AZ

**Comment by rquesada** [comment]
This PR is covered in PR#31

**Pull request closed without merging**
