### PR TITLE
Passkey Authentication

### PR DESCRIPTION
**Pull request by robertbinning**
Implementation of password-less authentication using WebAuthn.

### CODE REVIEW

**Comment by robertbinning** [comment]
I updated the README file per Karsten's request. The only known issue is sometimes when initializing the db and upgrading head, the user and public_key_cred tables already exist in Alembic. Current workaround is to manually drop those 2 tables using sqlite3 and then running 'alembic upgrade head' again. The app should then run fine. I will look into resolving this issue next

**Comment by samj** [comment]
Had a look at merging this just now but there's some outstanding issues:

- There's still some conflicts with the Base/SQLModelBase fixes that went in today. Would have fixed these but saw some datetime and relationship stuff and figured I probably wasn't the best person to play with it.
- I don't know Webauthn well enough to say what the API paths should be, but I'd think something like `/auth/login/start` and `/auth/logout` would be cleaner — your preferred Copilot may have views on this (mine did).
- I wasn't sure about handling cookies at the API level (rather than, say, React) with `Set-Cookie` sending the passkey challenge; maybe that's required for Webauthn to work in this context?
- Also wasn't sure about the addition of cookieAuth (presumably from the [Swagger examples](https://swagger.io/docs/specification/authentication/cookie-authentication/)) rather than [API Keys](https://swagger.io/docs/specification/authentication/api-keys/), [bearer tokens](https://swagger.io/docs/specification/authentication/bearer-authentication/), or even [OAuth 2.0](https://example.com/.well-known/openid-configuration) (maybe later?). Looks like [OpenAI uses bearer tokens](https://github.com/openai/openai-openapi/blob/master/openapi.yaml) (i.e., passes is in an `Authorization: Bearer <token>` header), which is probably what we should be doing too.
- Relative URLs should be used but 'localhost' is hardcoded in several places.
- pAI-OS branding needs updating from the branding repo.
- 'authenticated' is saved to localstorage, but the client doesn't know if it's authenticated (maybe its session timed out?) so I'm not sure this is what you want rather than e.g. assuming you're authenticated if you have a token, but redirecting back to login if the token is ever rejected?

I don't like sending PRs back but most of these really should be fixed first. Fortunately they're mostly fairly trivial.

**Comment by samj** [comment]
It's in `feat/passkeys` for now.

**Comment by samj** [comment]
OK so it took me the whole day but I've got this to a mergeable state, rebased onto develop, and fast-forwarded to it.

I've made some changes to the API to make way for future authentication mechanisms like OAuth, so the hooks are now:
- /auth/webauthn/register-options
- /auth/webauthn/register
- /auth/webauthn/login-options
- /auth/webauthn/login
- /auth/logout

I thought about doing a more involved session manager under /sessions so you can see who's currently connected, kick them off, etc. but that calls for a SessionManager etc. and there's no demand for it yet so we'll come back to it when there is.

I moved the utils back into AuthManager as utils is meant to be lightweght generic tools, and while I was at it I generalised the dotenv functionality from encryption.py so we can fetch the key from there (passing in a generator function as a default and using secrets to create a secure jwt secret).

I also split back out the tables which had been consolidated into a single migration and tweaked the fields and foreign keys for future extensibility.

It does seem to create new creds if you use the Register option again instead of using Login with an existing credential, which is almost certainly not what we want.

Here's a demo:

https://youtu.be/hlkWh6_JQdg

**Pull request closed without merging**
